name: .NET Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: build
        run: dotnet build

      - name: test
        run: dotnet test

      - name: pack core
        run: dotnet pack .\MessagingToolkit\MessagingToolkit.csproj -c RELEASE -o pack\core --include-source -p:Version=${{ github.ref_name }}

      - name: pack core
        run: dotnet pack .\MessagingToolkit.Wpf\MessagingToolkit.Wpf.csproj -c RELEASE -o pack\wpf --include-source -p:Version=${{ github.ref_name }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: 'pack/*'

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pack/*
            LICENSE
            README.md